---
- name: Deploy Java application to Minikube
  hosts: localhost
  connection: local

  vars_files:
    - vars.yml


  tasks:

    - name: Build Java application
      command:
        cmd: mvn clean package -DskipTests

    - name: Build Docker image
      command:
        cmd: docker build -t {{ image_name }}:{{ image_tag }} .

    - name: Load image into Minikube
      command:
        cmd: minikube image load {{ image_name }}:{{ image_tag }}

    - name: Generate Deployment Manifest
      template:
        src: templates/deployment.yml.j2
        dest: generated/deployment.yml

    - name: Generate Service Manifest
      template:
        src: templates/service.yml.j2
        dest: generated/service.yml

    - name: Apply Deployment
      command:
        cmd: kubectl apply -f generated/deployment.yml

    - name: Apply Service
      command:
        cmd: kubectl apply -f generated/service.yml

    - name: Wait for Deployment
      command:
        cmd: kubectl rollout status deployment/java-app -n {{ namespace }}